### ISSUE TITLE
Incorrect lengths for some country numbers

### ISSUE THREAD

**Issue by niravpatel-inventyv** [mohamadzoh/phonelib#1]
For some countries, the phone number extraction is not working correctly, leading to incorrect country code or number length when using the phonelib library. This issue is particularly evident with the following countries:
+ Germany (+4915123456789): Unable to extract country information.
+ Japan (+81312345678): Unable to extract country information.
germany should support 11 digits and else for many more countries
![image](https://github.com/user-attachments/assets/aab02f02-184c-4c83-9a0d-f30614db4c37)

**Comment by mohamadzoh** [comment]
Hi, I updated my dataset and uploaded a new version. Please let me know if you know any country with incorrect data so I can update the dataset accordingly.

**Comment by Itsoon** [comment]
## France (+33): National format with leading 0 not recognized

French national phone numbers have **10 digits** starting with 0 (e.g., `0645342545`), but the library only recognizes **9 digits** without the
leading zero.

### Current behavior

```rust
extract_phone_numbers_with_country_hint("645342545", "FR")
// Works: [ExtractedPhoneNumber { normalized: Some("+33645342545"), is_valid: true }]

extract_phone_numbers_with_country_hint("0645342545", "FR")
// Fails: [ExtractedPhoneNumber { normalized: None, is_valid: false }]
```

Root cause

The Country struct for France is defined with:

```rust
Country {
    name: "France",
    code: "FR",
    phone_lengths: &[9],  // Should be &[9, 10]
    prefix: 33,
}
```

Expected behavior

National format numbers starting with 0 should be recognized and normalized to E.164 format:

- Input: 0645342545 (10 digits)
- Expected: +33645342545
